#ifndef RME_MATERIALS_WORKBENCH_BRUSH_PANEL_H_
#define RME_MATERIALS_WORKBENCH_BRUSH_PANEL_H_

#include <functional>
#include <limits>

#include <wx/panel.h>

#include "brush_database.h"

class MaterialsWorkbenchController;
class wxButton;
class wxCheckBox;
class wxChoice;
class wxListBox;
class wxListCtrl;
class wxNotebook;
class wxMouseEvent;
class wxPanel;
class wxScrolledWindow;
class wxSimplebook;
class wxSizer;
class wxSpinCtrl;
class wxStaticText;
class wxTextCtrl;
class wxVListBox;

class MaterialsWorkbenchBrushPanel : public wxPanel {
public:
	static constexpr int kDoodadPreviewAllFloors = std::numeric_limits<int>::min();

	MaterialsWorkbenchBrushPanel(wxWindow* parent, MaterialsWorkbenchController &controller);

	void ClearWorkspace(const wxString &message);
	bool LoadBrush(const wxString &contextKey, int itemIndex);
	void SetOnBrushSaved(std::function<void(int64_t, const wxString &, const wxString &)> callback);
	void SetOnBrushDeleted(std::function<void(int64_t)> callback);
	void SetOnBrushStateChanged(std::function<void()> callback);
	void SetOnOpenLinkedBrush(std::function<void(int64_t)> callback);
	void SetOnOpenLinkedBorderSet(std::function<void(int64_t)> callback);
	void SetOnOpenLinkedTileset(std::function<void(const wxString &)> callback);
	bool HasPendingChanges() const;
	bool IsCurrentBrushSelection(const wxString &contextKey, int itemIndex) const;
	wxString GetCurrentBrushDisplayName() const;
	wxString GetCurrentBrushInspectorText() const;
	bool ResolvePendingChangesBeforeSwitch(wxWindow* parent, const wxString &targetLabel);

private:
	struct VariationEditorState {
		bool valid = false;
		int workspaceTabSelection = 0;
		int metadataViewX = -1;
		int metadataViewY = -1;
		int groundItemIndex = -1;
		int alignedNodeIndex = -1;
		int alignedItemIndex = -1;
		int doodadAlternativeIndex = -1;
		int doodadSingleItemIndex = -1;
		int doodadCompositeIndex = -1;
		int doodadTileIndex = -1;
		int doodadTileItemIndex = -1;
		int doodadPreviewFloor = kDoodadPreviewAllFloors;
		bool doodadPreviewPreferComposite = true;
		int groundTopItem = -1;
		int alignedNodesTopItem = -1;
		int alignedItemsTopItem = -1;
		int doodadAlternativesTopItem = -1;
		int doodadSingleItemsTopItem = -1;
		int doodadCompositesTopItem = -1;
		int doodadTilesTopItem = -1;
		int doodadTileItemsTopItem = -1;
	};

	struct AlignedEditorWidgets {
		wxPanel* page = nullptr;
		wxStaticText* sectionLabel = nullptr;
		wxStaticText* visualInfoLabel = nullptr;
		wxPanel* contextPanel = nullptr;
		wxButton* addNodeButton = nullptr;
		wxButton* addItemButton = nullptr;
		wxButton* removeItemButton = nullptr;
		wxStaticText* nodesDetailsLabel = nullptr;
		wxButton* nodesDetailsButton = nullptr;
		wxListBox* nodesList = nullptr;
		wxStaticText* seamlessPreviewInfoLabel = nullptr;
		wxPanel* seamlessPreviewPanel = nullptr;
		wxStaticText* itemsSummaryLabel = nullptr;
		wxScrolledWindow* itemsScroll = nullptr;
		wxPanel* itemsCardsPanel = nullptr;
		wxPanel* advancedPanel = nullptr;
		wxTextCtrl* nodeAlignCtrl = nullptr;
		wxChoice* nodeAlignChoice = nullptr;
		wxStaticText* advancedInfoLabel = nullptr;
		wxListBox* itemsList = nullptr;
		wxSpinCtrl* itemIdCtrl = nullptr;
		wxSpinCtrl* itemChanceCtrl = nullptr;
		wxStaticText* itemOwnershipLabel = nullptr;
	};

	void BuildLayout();
	wxPanel* BuildMetadataPage(wxNotebook* notebook);
	wxPanel* BuildVariationsPage(wxNotebook* notebook);
	wxPanel* BuildLinksPage(wxNotebook* notebook);
	wxPanel* BuildUnsupportedVariationsPage(wxSimplebook* book);
	wxPanel* BuildGroundVariationsPage(wxSimplebook* book);
	wxPanel* BuildCarpetVariationsPage(wxSimplebook* book);
	wxPanel* BuildTableVariationsPage(wxSimplebook* book);
	wxPanel* BuildDoodadVariationsPage(wxSimplebook* book);
	void SetActiveAlignedEditorWidgets(AlignedEditorWidgets* widgets);
	void PopulateFields();
	void PopulateMetadataFields();
	void UpdateSummary();
	void RefreshLinksPage();
	void ClearCurrentBrushBorders();
	void NormalizeLinkSortOrders();
	bool TryGetSelectedOutgoingLinkIndex(int &outIndex) const;
	void UpdateLinksButtonState();
	void EditSelectedOutgoingLink();
	void AddOutgoingLink(const wxString &relationType);
	void RemoveSelectedOutgoingLink();
	void ClearFriendEnemyLinks();
	void MoveSelectedOutgoingLink(int delta);
	void SetStatusMessage(const wxString &message);
	void SetFieldsEnabled(bool enabled);
	void ResetVariationSelection();
	void CommitVariationEditorState();
	void CommitGroundVariationEditorState();
	void CommitCarpetVariationEditorState();
	void CommitTableVariationEditorState();
	void CommitDoodadVariationEditorState();
	void RefreshVariationEditor();
	wxString GetVariationTabTitle() const;
	void RefreshGroundItemList();
	void RefreshGroundSelection();
	void RefreshGroundPreviewState();
	void RefreshGroundPreviewLayout();
	void RefreshAlignedNodeList();
	void RefreshAlignedItemList();
	void RefreshAlignedSelection();
	void RefreshAlignedVisualState();
	void RefreshAlignedSeamlessPreview();
	bool ShowTableItemDialog(const wxString &title, int &itemId, int &chance);
	void AddTableItemToNodeWithDialog(int nodeIndex);
	void EditTableItemWithDialog(int nodeIndex, int itemIndex);
	void RefreshDoodadAlternativeList();
	void RefreshDoodadSingleItemList();
	void RefreshDoodadCompositeList();
	void RefreshDoodadTileList();
	void RefreshDoodadTileItemList();
	void RefreshDoodadAlternativeSlider();
	void RefreshDoodadSelection();
	void RefreshDoodadPreviewFloorChoice();
	void RefreshDoodadPreview();
	void NormalizeVariationSortOrders();
	BrushStorageRecord BuildEditableStorageFromCurrentState() const;
	void RefreshDirtyState();
	void RefreshLiveDoodadRuntime(const BrushStorageRecord &editableStorage);
	void NotifyBrushStateChanged();
	void UpdateWorkspaceHeader();
	void UpdateActionButtons();
	void UpdateModifiedHighlights();
	void UpdateMetadataModifiedHighlights(const BrushRecord &editableBrush);
	void UpdateVariationModifiedHighlights(const BrushStorageRecord &editableStorage);
	void UpdateItemOwnershipHint(wxStaticText* label, int itemId, bool hasSelection) const;
	void RefreshLookIdPreviews();
	void RefreshLookIdOwnershipHints() const;
	bool TryGetRuntimeBrushOwnerName(int itemId, wxString &ownerName) const;
	bool IsCurrentBrushOwnerName(const wxString &ownerName) const;
	VariationEditorState CaptureVariationEditorState() const;
	void RestoreVariationEditorState(const VariationEditorState &state);
	bool SaveCurrentBrush();
	bool ValidateBrushStorage(wxString &error) const;
	wxString GetEffectiveBrushType() const;
	bool UsesGroundVariationEditor() const;
	bool UsesAlignedVariationEditor() const;
	bool UsesDoodadVariationEditor() const;

	void OnSave(wxCommandEvent &event);
	void OnRevert(wxCommandEvent &event);
	void OnAddGroundItem(wxCommandEvent &event);
	void OnRemoveGroundItem(wxCommandEvent &event);
	void OnGroundItemSelected(wxCommandEvent &event);
	void OnGroundCardsPaint(wxPaintEvent &event);
	void OnGroundCardsLeftDown(wxMouseEvent &event);
	void OnGroundCardsRightDown(wxMouseEvent &event);
	void OnGroundPreviewPaint(wxPaintEvent &event);
	void OnGroundPreviewLeftDown(wxMouseEvent &event);
	void OnGroundPreviewMotion(wxMouseEvent &event);
	void OnGroundPreviewMouseLeave(wxMouseEvent &event);
	void OnGroundPreviewSize(wxSizeEvent &event);
	void OnGroundPreviewHighlightToggled(wxCommandEvent &event);
	void OnGroundItemValueChanged(wxCommandEvent &event);
	void OnAddAlignedNode(wxCommandEvent &event);
	void OnRemoveAlignedNode(wxCommandEvent &event);
	void OnAlignedNodeSelected(wxCommandEvent &event);
	void OnAlignedNodeAlignChanged(wxCommandEvent &event);
	void OnAddAlignedItem(wxCommandEvent &event);
	void OnRemoveAlignedItem(wxCommandEvent &event);
	void OnAlignedItemSelected(wxCommandEvent &event);
	void OnAlignedItemValueChanged(wxCommandEvent &event);
	void OnAlignedContextPaint(wxPaintEvent &event);
	void OnAlignedContextLeftDown(wxMouseEvent &event);
	void OnAlignedContextMotion(wxMouseEvent &event);
	void OnAlignedContextMouseLeave(wxMouseEvent &event);
	void OnAlignedSeamlessPreviewPaint(wxPaintEvent &event);
	void OnAlignedItemsCardsPaint(wxPaintEvent &event);
	void OnAlignedItemsCardsLeftDown(wxMouseEvent &event);
	void OnAlignedItemsCardsRightDown(wxMouseEvent &event);
	void OnAlignedNodesDetailsToggled(wxCommandEvent &event);
	void OnAddDoodadAlternative(wxCommandEvent &event);
	void OnRemoveDoodadAlternative(wxCommandEvent &event);
	void OnAddDoodadSingleItem(wxCommandEvent &event);
	void OnRemoveDoodadSingleItem(wxCommandEvent &event);
	void OnDoodadSingleItemSelected(wxCommandEvent &event);
	void OnDoodadSingleItemRightDown(wxMouseEvent &event);
	void OnDoodadSingleItemValueChanged(wxCommandEvent &event);
	void OnAddDoodadComposite(wxCommandEvent &event);
	void OnRemoveDoodadComposite(wxCommandEvent &event);
	void OnDoodadCompositeSelected(wxCommandEvent &event);
	void OnDoodadCompositeRightDown(wxMouseEvent &event);
	void OnDoodadCompositeChanceChanged(wxCommandEvent &event);
	void OnAddDoodadTile(wxCommandEvent &event);
	void OnRemoveDoodadTile(wxCommandEvent &event);
	void OnDoodadTileSelected(wxCommandEvent &event);
	void OnDoodadTileOffsetChanged(wxCommandEvent &event);
	void OnAddDoodadTileItem(wxCommandEvent &event);
	void OnRemoveDoodadTileItem(wxCommandEvent &event);
	void OnDoodadTileItemSelected(wxCommandEvent &event);
	void OnDoodadTileItemRightDown(wxMouseEvent &event);
	void OnDoodadTileItemValueChanged(wxCommandEvent &event);
	void OnDoodadPreviewPaint(wxPaintEvent &event);
	void OnDoodadPreviewLeftDown(wxMouseEvent &event);
	void OnDoodadPreviewRightDown(wxMouseEvent &event);
	void OnDoodadAlternativeSliderPaint(wxPaintEvent &event);
	void OnDoodadAlternativeSliderLeftDown(wxMouseEvent &event);
	void OnDoodadFloorSliderPaint(wxPaintEvent &event);
	void OnDoodadFloorSliderLeftDown(wxMouseEvent &event);
	void OnMetadataFieldChanged(wxCommandEvent &event);
	void OnCreateBrush(wxCommandEvent &event);
	void OnDeleteBrush(wxCommandEvent &event);
	void OnUsedBy(wxCommandEvent &event);
	void OnOpenSelectedOutgoingLinkTarget(wxCommandEvent &event);
	void SelectDoodadAlternative(int index);
	void StepDoodadAlternative(int delta);
	void StepDoodadPreviewFloor(int delta);
	void AddDoodadPreviewFloor();
	void RemoveDoodadPreviewFloor();

	MaterialsWorkbenchController &controller_;
	std::function<void(int64_t, const wxString &, const wxString &)> onBrushSaved_;
	std::function<void(int64_t)> onBrushDeleted_;
	std::function<void()> onBrushStateChanged_;
	std::function<void(int64_t)> onOpenLinkedBrush_;
	std::function<void(int64_t)> onOpenLinkedBorderSet_;
	std::function<void(const wxString &)> onOpenLinkedTileset_;
	BrushStorageRecord brushStorage_;
	BrushStorageRecord loadedBrushStorage_;
	BrushStorageRecord runtimeSyncedBrushStorage_;
	wxString currentContextKey_;
	int currentItemIndex_ = -1;
	bool hasBrush_ = false;
	bool internalUpdate_ = false;
	bool dirty_ = false;
	bool hasRuntimeSyncedBrushStorage_ = false;
	wxString lastConfirmedType_;

	wxNotebook* workspaceTabs_ = nullptr;
	wxScrolledWindow* metadataPage_ = nullptr;
	wxPanel* linksPage_ = nullptr;
	wxStaticText* titleLabel_ = nullptr;
	wxStaticText* subtitleLabel_ = nullptr;
	wxStaticText* summaryLabel_ = nullptr;
	wxStaticText* variationsStatusLabel_ = nullptr;
	wxButton* createBrushButton_ = nullptr;
	wxButton* deleteBrushButton_ = nullptr;
	wxButton* usedByButton_ = nullptr;
	wxButton* saveButton_ = nullptr;
	wxButton* revertButton_ = nullptr;
	wxTextCtrl* nameCtrl_ = nullptr;
	wxChoice* typeCtrl_ = nullptr;
	wxTextCtrl* idCtrl_ = nullptr;
	wxTextCtrl* storageCtrl_ = nullptr;
	wxTextCtrl* sourceCtrl_ = nullptr;
	wxSpinCtrl* lookIdCtrl_ = nullptr;
	wxSpinCtrl* serverLookIdCtrl_ = nullptr;
	wxPanel* lookIdPreview_ = nullptr;
	wxPanel* serverLookIdPreview_ = nullptr;
	wxStaticText* lookIdOwnershipLabel_ = nullptr;
	wxStaticText* serverLookIdOwnershipLabel_ = nullptr;
	wxSpinCtrl* zOrderCtrl_ = nullptr;
	wxSpinCtrl* thicknessCtrl_ = nullptr;
	wxSpinCtrl* thicknessCeilingCtrl_ = nullptr;
	wxCheckBox* draggableCtrl_ = nullptr;
	wxCheckBox* onBlockingCtrl_ = nullptr;
	wxCheckBox* onDuplicateCtrl_ = nullptr;
	wxCheckBox* redoBordersCtrl_ = nullptr;
	wxCheckBox* removeOptionalBorderCtrl_ = nullptr;
	wxCheckBox* randomizeCtrl_ = nullptr;
	wxCheckBox* oneSizeCtrl_ = nullptr;
	wxCheckBox* soloOptionalCtrl_ = nullptr;
	wxStaticText* bordersQuickSummaryLabel_ = nullptr;
	wxButton* clearBordersButton_ = nullptr;
	wxTextCtrl* linksSearchCtrl_ = nullptr;
	wxStaticText* linksSummaryLabel_ = nullptr;
	wxListCtrl* linksListCtrl_ = nullptr;
	wxStaticText* linksInboundSummaryLabel_ = nullptr;
	wxListCtrl* linksInboundListCtrl_ = nullptr;
	wxButton* addFriendLinkButton_ = nullptr;
	wxButton* addEnemyLinkButton_ = nullptr;
	wxButton* openLinkTargetButton_ = nullptr;
	wxButton* removeLinkButton_ = nullptr;
	wxButton* clearLinksButton_ = nullptr;
	wxButton* moveLinkUpButton_ = nullptr;
	wxButton* moveLinkDownButton_ = nullptr;
	wxSimplebook* variationsBook_ = nullptr;
	wxStaticText* variationsEmptyLabel_ = nullptr;
	wxListBox* groundItemsList_ = nullptr;
	wxScrolledWindow* groundItemsScroll_ = nullptr;
	wxPanel* groundItemsCardsPanel_ = nullptr;
	wxSpinCtrl* groundItemIdCtrl_ = nullptr;
	wxSpinCtrl* groundItemChanceCtrl_ = nullptr;
	wxStaticText* groundItemOwnershipLabel_ = nullptr;
	wxScrolledWindow* groundPreviewScroll_ = nullptr;
	wxPanel* groundPreviewPanel_ = nullptr;
	wxStaticText* groundPreviewInfoLabel_ = nullptr;
	wxStaticText* groundPreviewDistributionLabel_ = nullptr;
	wxCheckBox* groundPreviewHighlightCtrl_ = nullptr;
	std::vector<wxRect> groundItemCardRects_;
	std::vector<wxRect> groundPreviewTileRects_;
	bool groundPreviewHighlightEnabled_ = false;
	int groundItemIndex_ = -1;
	AlignedEditorWidgets carpetAlignedWidgets_;
	AlignedEditorWidgets tableAlignedWidgets_;
	wxStaticText* alignedSectionLabel_ = nullptr;
	wxStaticText* alignedVisualInfoLabel_ = nullptr;
	wxPanel* alignedContextPanel_ = nullptr;
	wxButton* alignedAddNodeButton_ = nullptr;
	wxButton* alignedAddItemButton_ = nullptr;
	wxButton* alignedRemoveItemButton_ = nullptr;
	wxStaticText* alignedNodesDetailsLabel_ = nullptr;
	wxButton* alignedNodesDetailsButton_ = nullptr;
	wxListBox* alignedNodesList_ = nullptr;
	wxStaticText* alignedSeamlessPreviewInfoLabel_ = nullptr;
	wxPanel* alignedSeamlessPreviewPanel_ = nullptr;
	wxStaticText* alignedItemsSummaryLabel_ = nullptr;
	wxScrolledWindow* alignedItemsScroll_ = nullptr;
	wxPanel* alignedItemsCardsPanel_ = nullptr;
	wxPanel* alignedAdvancedPanel_ = nullptr;
	wxTextCtrl* alignedNodeAlignCtrl_ = nullptr;
	wxChoice* alignedNodeAlignChoice_ = nullptr;
	wxStaticText* alignedAdvancedInfoLabel_ = nullptr;
	wxListBox* alignedItemsList_ = nullptr;
	wxSpinCtrl* alignedItemIdCtrl_ = nullptr;
	wxSpinCtrl* alignedItemChanceCtrl_ = nullptr;
	wxStaticText* alignedItemOwnershipLabel_ = nullptr;
	std::vector<wxRect> alignedContextRects_;
	std::vector<wxRect> alignedContextAddRects_;
	std::vector<wxString> alignedContextRectAligns_;
	std::vector<wxString> alignedContextRectTooltips_;
	std::vector<wxRect> alignedItemCardRects_;
	std::vector<wxRect> alignedItemEditRects_;
	std::vector<wxRect> alignedItemRemoveRects_;
	bool alignedNodesDetailsExpanded_ = false;
	int alignedNodeIndex_ = -1;
	int alignedItemIndex_ = -1;
	wxString alignedPendingCarpetAlign_;
	wxString alignedPendingTableAlign_;
	wxPanel* doodadAlternativeSliderPanel_ = nullptr;
	wxRect doodadAlternativePrevRect_;
	wxRect doodadAlternativeNextRect_;
	wxRect doodadAlternativeAddRect_;
	wxRect doodadAlternativeRemoveRect_;
	std::vector<wxRect> doodadAlternativeIndicatorRects_;
	wxVListBox* doodadSingleItemsList_ = nullptr;
	wxSpinCtrl* doodadSingleItemIdCtrl_ = nullptr;
	wxSpinCtrl* doodadSingleItemChanceCtrl_ = nullptr;
	wxStaticText* doodadSingleItemOwnershipLabel_ = nullptr;
	wxListBox* doodadCompositesList_ = nullptr;
	wxSpinCtrl* doodadCompositeChanceCtrl_ = nullptr;
	wxStaticText* doodadPreviewSummaryLabel_ = nullptr;
	wxStaticText* doodadPreviewHintLabel_ = nullptr;
	wxPanel* doodadPreviewPanel_ = nullptr;
	wxPanel* doodadPreviewFloorSliderPanel_ = nullptr;
	wxRect doodadPreviewFloorAddRect_;
	wxRect doodadPreviewFloorUpRect_;
	wxRect doodadPreviewFloorDownRect_;
	wxRect doodadPreviewFloorRemoveRect_;
	std::vector<wxRect> doodadPreviewFloorIndicatorRects_;
	wxListBox* doodadTilesList_ = nullptr;
	wxSpinCtrl* doodadTileOffsetXCtrl_ = nullptr;
	wxSpinCtrl* doodadTileOffsetYCtrl_ = nullptr;
	wxSpinCtrl* doodadTileOffsetZCtrl_ = nullptr;
	wxVListBox* doodadTileItemsList_ = nullptr;
	wxSpinCtrl* doodadTileItemIdCtrl_ = nullptr;
	wxStaticText* doodadTileItemOwnershipLabel_ = nullptr;
	int doodadAlternativeIndex_ = -1;
	int doodadSingleItemIndex_ = -1;
	int doodadCompositeIndex_ = -1;
	int doodadTileIndex_ = -1;
	int doodadTileItemIndex_ = -1;
	int doodadPreviewFloor_ = kDoodadPreviewAllFloors;
	bool doodadPreviewPreferComposite_ = true;
	std::vector<int> doodadPreviewAvailableFloors_;
	std::vector<int> doodadPreviewAuthoringFloors_;
	wxStaticText* statusLabel_ = nullptr;
};

#endif
