#ifndef RME_MATERIALS_WORKBENCH_BRUSH_PANEL_H_
#define RME_MATERIALS_WORKBENCH_BRUSH_PANEL_H_

#include <functional>
#include <limits>

#include <wx/panel.h>

#include "brush_database.h"

class MaterialsWorkbenchController;
class wxButton;
class wxCheckBox;
class wxChoice;
class wxListBox;
class wxNotebook;
class wxMouseEvent;
class wxPanel;
class wxScrolledWindow;
class wxSimplebook;
class wxSizer;
class wxSpinCtrl;
class wxStaticText;
class wxTextCtrl;

class MaterialsWorkbenchBrushPanel : public wxPanel {
public:
	static constexpr int kDoodadPreviewAllFloors = std::numeric_limits<int>::min();

	MaterialsWorkbenchBrushPanel(wxWindow* parent, MaterialsWorkbenchController &controller);

	void ClearWorkspace(const wxString &message);
	bool LoadBrush(const wxString &contextKey, int itemIndex);
	void SetOnBrushSaved(std::function<void(int64_t, const wxString&, const wxString&)> callback);
	void SetOnBrushStateChanged(std::function<void()> callback);
	bool HasPendingChanges() const;
	bool IsCurrentBrushSelection(const wxString &contextKey, int itemIndex) const;
	wxString GetCurrentBrushDisplayName() const;
	wxString GetCurrentBrushInspectorText() const;
	bool ResolvePendingChangesBeforeSwitch(wxWindow* parent, const wxString &targetLabel);

private:
	struct VariationEditorState {
		bool valid = false;
		int workspaceTabSelection = 0;
		int metadataViewX = -1;
		int metadataViewY = -1;
		int groundItemIndex = -1;
		int alignedNodeIndex = -1;
		int alignedItemIndex = -1;
		int doodadAlternativeIndex = -1;
		int doodadSingleItemIndex = -1;
		int doodadCompositeIndex = -1;
		int doodadTileIndex = -1;
		int doodadTileItemIndex = -1;
		int doodadPreviewFloor = kDoodadPreviewAllFloors;
		bool doodadPreviewPreferComposite = true;
		int groundTopItem = -1;
		int alignedNodesTopItem = -1;
		int alignedItemsTopItem = -1;
		int doodadAlternativesTopItem = -1;
		int doodadSingleItemsTopItem = -1;
		int doodadCompositesTopItem = -1;
		int doodadTilesTopItem = -1;
		int doodadTileItemsTopItem = -1;
	};

	void BuildLayout();
	wxPanel* BuildMetadataPage(wxNotebook* notebook);
	wxPanel* BuildVariationsPage(wxNotebook* notebook);
	wxPanel* BuildUnsupportedVariationsPage(wxSimplebook* book);
	wxPanel* BuildGroundVariationsPage(wxSimplebook* book);
	wxPanel* BuildAlignedVariationsPage(wxSimplebook* book);
	wxPanel* BuildDoodadVariationsPage(wxSimplebook* book);
	void PopulateFields();
	void PopulateMetadataFields();
	void UpdateSummary();
	void SetStatusMessage(const wxString &message);
	void SetFieldsEnabled(bool enabled);
	void ResetVariationSelection();
	void CommitVariationEditorState();
	void RefreshVariationEditor();
	void RefreshGroundItemList();
	void RefreshGroundSelection();
	void RefreshGroundPreviewState();
	void RefreshGroundPreviewLayout();
	void RefreshAlignedNodeList();
	void RefreshAlignedItemList();
	void RefreshAlignedSelection();
	void RefreshAlignedVisualState();
	void RefreshDoodadAlternativeList();
	void RefreshDoodadSingleItemList();
	void RefreshDoodadCompositeList();
	void RefreshDoodadTileList();
	void RefreshDoodadTileItemList();
	void RefreshDoodadAlternativeSlider();
	void RefreshDoodadSelection();
	void RefreshDoodadPreviewFloorChoice();
	void RefreshDoodadPreview();
	void NormalizeVariationSortOrders();
	BrushStorageRecord BuildEditableStorageFromCurrentState() const;
	void RefreshDirtyState();
	void RefreshLiveDoodadRuntime(const BrushStorageRecord &editableStorage);
	void NotifyBrushStateChanged();
	void UpdateWorkspaceHeader();
	void UpdateActionButtons();
	void UpdateModifiedHighlights();
	void UpdateMetadataModifiedHighlights(const BrushRecord &editableBrush);
	void UpdateVariationModifiedHighlights(const BrushStorageRecord &editableStorage);
	void UpdateItemOwnershipHint(wxStaticText* label, int itemId, bool hasSelection) const;
	void RefreshLookIdOwnershipHints() const;
	bool TryGetRuntimeBrushOwnerName(int itemId, wxString &ownerName) const;
	bool IsCurrentBrushOwnerName(const wxString &ownerName) const;
	VariationEditorState CaptureVariationEditorState() const;
	void RestoreVariationEditorState(const VariationEditorState &state);
	bool SaveCurrentBrush();
	bool ValidateBrushStorage(wxString &error) const;
	wxString GetEffectiveBrushType() const;
	bool UsesGroundVariationEditor() const;
	bool UsesAlignedVariationEditor() const;
	bool UsesDoodadVariationEditor() const;

	void OnSave(wxCommandEvent &event);
	void OnRevert(wxCommandEvent &event);
	void OnAddGroundItem(wxCommandEvent &event);
	void OnRemoveGroundItem(wxCommandEvent &event);
	void OnGroundItemSelected(wxCommandEvent &event);
	void OnGroundCardsPaint(wxPaintEvent &event);
	void OnGroundCardsLeftDown(wxMouseEvent &event);
	void OnGroundCardsRightDown(wxMouseEvent &event);
	void OnGroundPreviewPaint(wxPaintEvent &event);
	void OnGroundPreviewLeftDown(wxMouseEvent &event);
	void OnGroundPreviewMotion(wxMouseEvent &event);
	void OnGroundPreviewMouseLeave(wxMouseEvent &event);
	void OnGroundPreviewSize(wxSizeEvent &event);
	void OnGroundPreviewHighlightToggled(wxCommandEvent &event);
	void OnGroundItemValueChanged(wxCommandEvent &event);
	void OnAddAlignedNode(wxCommandEvent &event);
	void OnRemoveAlignedNode(wxCommandEvent &event);
	void OnAlignedNodeSelected(wxCommandEvent &event);
	void OnAlignedNodeAlignChanged(wxCommandEvent &event);
	void OnAddAlignedItem(wxCommandEvent &event);
	void OnRemoveAlignedItem(wxCommandEvent &event);
	void OnAlignedItemSelected(wxCommandEvent &event);
	void OnAlignedItemValueChanged(wxCommandEvent &event);
	void OnAlignedContextPaint(wxPaintEvent &event);
	void OnAlignedContextLeftDown(wxMouseEvent &event);
	void OnAlignedItemsCardsPaint(wxPaintEvent &event);
	void OnAlignedItemsCardsLeftDown(wxMouseEvent &event);
	void OnAlignedItemsCardsRightDown(wxMouseEvent &event);
	void OnAddDoodadAlternative(wxCommandEvent &event);
	void OnRemoveDoodadAlternative(wxCommandEvent &event);
	void OnAddDoodadSingleItem(wxCommandEvent &event);
	void OnRemoveDoodadSingleItem(wxCommandEvent &event);
	void OnDoodadSingleItemSelected(wxCommandEvent &event);
	void OnDoodadSingleItemRightDown(wxMouseEvent &event);
	void OnDoodadSingleItemValueChanged(wxCommandEvent &event);
	void OnAddDoodadComposite(wxCommandEvent &event);
	void OnRemoveDoodadComposite(wxCommandEvent &event);
	void OnDoodadCompositeSelected(wxCommandEvent &event);
	void OnDoodadCompositeRightDown(wxMouseEvent &event);
	void OnDoodadCompositeChanceChanged(wxCommandEvent &event);
	void OnAddDoodadTile(wxCommandEvent &event);
	void OnRemoveDoodadTile(wxCommandEvent &event);
	void OnDoodadTileSelected(wxCommandEvent &event);
	void OnDoodadTileOffsetChanged(wxCommandEvent &event);
	void OnAddDoodadTileItem(wxCommandEvent &event);
	void OnRemoveDoodadTileItem(wxCommandEvent &event);
	void OnDoodadTileItemSelected(wxCommandEvent &event);
	void OnDoodadTileItemRightDown(wxMouseEvent &event);
	void OnDoodadTileItemValueChanged(wxCommandEvent &event);
	void OnDoodadPreviewPaint(wxPaintEvent &event);
	void OnDoodadPreviewLeftDown(wxMouseEvent &event);
	void OnDoodadPreviewRightDown(wxMouseEvent &event);
	void OnDoodadAlternativeSliderPaint(wxPaintEvent &event);
	void OnDoodadAlternativeSliderLeftDown(wxMouseEvent &event);
	void OnDoodadFloorSliderPaint(wxPaintEvent &event);
	void OnDoodadFloorSliderLeftDown(wxMouseEvent &event);
	void OnMetadataFieldChanged(wxCommandEvent &event);
	void SelectDoodadAlternative(int index);
	void StepDoodadAlternative(int delta);
	void StepDoodadPreviewFloor(int delta);
	void AddDoodadPreviewFloor();
	void RemoveDoodadPreviewFloor();

	MaterialsWorkbenchController &controller_;
	std::function<void(int64_t, const wxString&, const wxString&)> onBrushSaved_;
	std::function<void()> onBrushStateChanged_;
	BrushStorageRecord brushStorage_;
	BrushStorageRecord loadedBrushStorage_;
	BrushStorageRecord runtimeSyncedBrushStorage_;
	wxString currentContextKey_;
	int currentItemIndex_ = -1;
	bool hasBrush_ = false;
	bool internalUpdate_ = false;
	bool dirty_ = false;
	bool hasRuntimeSyncedBrushStorage_ = false;

	wxNotebook* workspaceTabs_ = nullptr;
	wxScrolledWindow* metadataPage_ = nullptr;
	wxStaticText* titleLabel_ = nullptr;
	wxStaticText* subtitleLabel_ = nullptr;
	wxStaticText* summaryLabel_ = nullptr;
	wxStaticText* variationsStatusLabel_ = nullptr;
	wxButton* saveButton_ = nullptr;
	wxButton* revertButton_ = nullptr;
	wxTextCtrl* nameCtrl_ = nullptr;
	wxTextCtrl* typeCtrl_ = nullptr;
	wxTextCtrl* idCtrl_ = nullptr;
	wxTextCtrl* storageCtrl_ = nullptr;
	wxTextCtrl* sourceCtrl_ = nullptr;
	wxSpinCtrl* lookIdCtrl_ = nullptr;
	wxSpinCtrl* serverLookIdCtrl_ = nullptr;
	wxStaticText* lookIdOwnershipLabel_ = nullptr;
	wxStaticText* serverLookIdOwnershipLabel_ = nullptr;
	wxSpinCtrl* zOrderCtrl_ = nullptr;
	wxSpinCtrl* thicknessCtrl_ = nullptr;
	wxSpinCtrl* thicknessCeilingCtrl_ = nullptr;
	wxCheckBox* draggableCtrl_ = nullptr;
	wxCheckBox* onBlockingCtrl_ = nullptr;
	wxCheckBox* onDuplicateCtrl_ = nullptr;
	wxCheckBox* redoBordersCtrl_ = nullptr;
	wxCheckBox* randomizeCtrl_ = nullptr;
	wxCheckBox* oneSizeCtrl_ = nullptr;
	wxCheckBox* soloOptionalCtrl_ = nullptr;
	wxSimplebook* variationsBook_ = nullptr;
	wxStaticText* variationsEmptyLabel_ = nullptr;
	wxListBox* groundItemsList_ = nullptr;
	wxScrolledWindow* groundItemsScroll_ = nullptr;
	wxPanel* groundItemsCardsPanel_ = nullptr;
	wxSpinCtrl* groundItemIdCtrl_ = nullptr;
	wxSpinCtrl* groundItemChanceCtrl_ = nullptr;
	wxStaticText* groundItemOwnershipLabel_ = nullptr;
	wxScrolledWindow* groundPreviewScroll_ = nullptr;
	wxPanel* groundPreviewPanel_ = nullptr;
	wxStaticText* groundPreviewInfoLabel_ = nullptr;
	wxStaticText* groundPreviewDistributionLabel_ = nullptr;
	wxCheckBox* groundPreviewHighlightCtrl_ = nullptr;
	std::vector<wxRect> groundItemCardRects_;
	std::vector<wxRect> groundPreviewTileRects_;
	bool groundPreviewHighlightEnabled_ = false;
	int groundItemIndex_ = -1;
	wxStaticText* alignedSectionLabel_ = nullptr;
	wxStaticText* alignedVisualInfoLabel_ = nullptr;
	wxPanel* alignedContextPanel_ = nullptr;
	wxListBox* alignedNodesList_ = nullptr;
	wxStaticText* alignedItemsSummaryLabel_ = nullptr;
	wxScrolledWindow* alignedItemsScroll_ = nullptr;
	wxPanel* alignedItemsCardsPanel_ = nullptr;
	wxTextCtrl* alignedNodeAlignCtrl_ = nullptr;
	wxListBox* alignedItemsList_ = nullptr;
	wxSpinCtrl* alignedItemIdCtrl_ = nullptr;
	wxSpinCtrl* alignedItemChanceCtrl_ = nullptr;
	wxStaticText* alignedItemOwnershipLabel_ = nullptr;
	std::vector<wxRect> alignedContextRects_;
	std::vector<wxString> alignedContextRectAligns_;
	std::vector<wxRect> alignedItemCardRects_;
	int alignedNodeIndex_ = -1;
	int alignedItemIndex_ = -1;
	wxPanel* doodadAlternativeSliderPanel_ = nullptr;
	wxRect doodadAlternativePrevRect_;
	wxRect doodadAlternativeNextRect_;
	wxRect doodadAlternativeAddRect_;
	wxRect doodadAlternativeRemoveRect_;
	std::vector<wxRect> doodadAlternativeIndicatorRects_;
	wxListBox* doodadSingleItemsList_ = nullptr;
	wxSpinCtrl* doodadSingleItemIdCtrl_ = nullptr;
	wxSpinCtrl* doodadSingleItemChanceCtrl_ = nullptr;
	wxStaticText* doodadSingleItemOwnershipLabel_ = nullptr;
	wxListBox* doodadCompositesList_ = nullptr;
	wxSpinCtrl* doodadCompositeChanceCtrl_ = nullptr;
	wxStaticText* doodadPreviewSummaryLabel_ = nullptr;
	wxStaticText* doodadPreviewHintLabel_ = nullptr;
	wxPanel* doodadPreviewPanel_ = nullptr;
	wxPanel* doodadPreviewFloorSliderPanel_ = nullptr;
	wxRect doodadPreviewFloorAddRect_;
	wxRect doodadPreviewFloorUpRect_;
	wxRect doodadPreviewFloorDownRect_;
	wxRect doodadPreviewFloorRemoveRect_;
	std::vector<wxRect> doodadPreviewFloorIndicatorRects_;
	wxListBox* doodadTilesList_ = nullptr;
	wxSpinCtrl* doodadTileOffsetXCtrl_ = nullptr;
	wxSpinCtrl* doodadTileOffsetYCtrl_ = nullptr;
	wxSpinCtrl* doodadTileOffsetZCtrl_ = nullptr;
	wxListBox* doodadTileItemsList_ = nullptr;
	wxSpinCtrl* doodadTileItemIdCtrl_ = nullptr;
	wxStaticText* doodadTileItemOwnershipLabel_ = nullptr;
	int doodadAlternativeIndex_ = -1;
	int doodadSingleItemIndex_ = -1;
	int doodadCompositeIndex_ = -1;
	int doodadTileIndex_ = -1;
	int doodadTileItemIndex_ = -1;
	int doodadPreviewFloor_ = kDoodadPreviewAllFloors;
	bool doodadPreviewPreferComposite_ = true;
	std::vector<int> doodadPreviewAvailableFloors_;
	std::vector<int> doodadPreviewAuthoringFloors_;
	wxStaticText* statusLabel_ = nullptr;
};

#endif
